app_tournament:
    resource: "@AppBundle/Controller/TournamentController.php"
    type:     annotation
app_equipos:
    resource: "@AppBundle/Controller/TeamController.php"
    type:     annotation
app_api:
    resource: "@AppBundle/Controller/ApiController.php"
    type:     annotation
app_player:
    resource: "@AppBundle/Controller/PlayerController.php"
    type:     annotation
app:
    #resource: '@AppBundle/Controller/'
    #type: annotation
    resource: '@AppBundle/Resources/config/routing.yml'
    prefix: /

#backend:
#    resource: "@BackendBundle/Resources/config/routing.yml"
#    prefix:   /

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

#fos_user:
#    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

#hwi_oauth_redirect:
#    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
#    prefix:   /login/connect

#facebook_login:
#    path: /login/login_facebook

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

#HWIOAuthBundle routes
hwi_oauth_security:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix: /login

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix: /login

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /login

facebook_login:
    path: /login/check-facebook
    #path: /login/facebook

google_login:
    path: /login/check-google

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

adesigns_calendar:
    resource: "@ADesignsCalendarBundle/Resources/config/routing.xml"
