# app/config/security.yml
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                login_path: /login
                check_path: /login_check
                # if you are using Symfony < 2.8, use the following config instead:
                # csrf_provider: form.csrf_provider
            remember_me:
                secret:      "%secret%"
                lifetime: 1200 # 1 week in seconds
                path:     /



            oauth:
                resource_owners:
                    facebook:           "/login/check-facebook"
                    google:             "/login/check-google"
                login_path:        /login
                failure_path: /login
                oauth_user_provider:
                    service: my_user_provider

            # Turn on anonymous for testings need.
            #anonymous: ~

            logout:       true
            anonymous:    true

        login:
            pattern:  ^/login$
            security: false

            remember_me:
                secret: "%secret%"
                #lifetime: 31536000 # 365 days in seconds
                lifetime: 1200
                path: /
                #always_remember_me: true
            #   domain: ~ # Defaults to the current domain from $_SERVER


    access_control:
        - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, role: ROLE_ADMIN }
        - { path: ^/, role: ROLE_USER }
