services:
    app_bundle.service.listener:
        class: AppBundle\EventListener\CalendarEventListener
        arguments: [ "@doctrine.orm.entity_manager" ]
        tags:
           - { name: 'kernel.event_listener', event: 'calendar.load_data', method: onloadData }
           #- { name: kernel.event_listener, event: calendar.load_events, method: loadEvents }

    my_user_provider:
        class: AppBundle\Security\Core\User\FOSUBUserProvider
        arguments: ['@fos_user.user_manager',{facebook: facebook_id,google: google_id}]

    app.form.registration:
        class: AppBundle\Form\RegistrationType
        tags:
           - { name: form.type, alias: app_user_registration }

    app.service.excel.reader:
        class: AppBundle\Service\ExcelReaderService
