<?php

namespace BackendBundle\Repository;

use BackendBundle\Entity\Tournament;
use  Doctrine\ORM\Query\Expr;

/**
 * EquiposRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeamRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByTournamentQuery(Tournament $tournament = null)
    {
        $query = $this->createQueryBuilder('tm');
        $query->orderby('tm.id','desc');
        if ($tournament) {
            $query
                ->leftJoin('tm.tournaments', 'tr')
                ->where('tr.id = :tournament_id')
                ->setParameter('tournament_id', $tournament->getId())
            ;
        }
        return $query->getQuery();
    }
}
