<?php

namespace BackendBundle\Repository;

use BackendBundle\Entity\User;
use BackendBundle\Entity\Tournament;
/**
 * TorneosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TournamentTeamRepository extends \Doctrine\ORM\EntityRepository
{
    public function teamByGroup(Tournament $tournament)
    {
        return $this->createQueryBuilder('tt')
            ->where('tt.tournament = :tournament')
            ->orderBy('tt.group', 'ASC')
            ->setParameter('tournament', $tournament)
            ->getQuery()
            ->getResult()
        ;
    }
}
