<?php

namespace BackendBundle\Repository;

use BackendBundle\Entity\User;
use BackendBundle\Entity\Tournament;
/**
 * TorneosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TournamentGameRepository extends \Doctrine\ORM\EntityRepository
{
    public function gameByRound(Tournament $tournament)
    {
        return $this->createQueryBuilder('tg')
            ->leftJoin('tg.homeTeam', 'tt')
            ->where('tt.tournament = :tournament')
            ->orderBy('tg.round', 'ASC')
            ->setParameter('tournament', $tournament)
            ->getQuery()
            ->getResult()
        ;
    }

    public function gameByGroup(Tournament $tournament)
    {
        return $this->createQueryBuilder('tg')
            ->leftJoin('tg.homeTeam', 'tt')
            ->where('tt.tournament = :tournament')
            ->orderBy('tt.group', 'ASC')
            ->orderBy('tg.round', 'ASC')
            ->setParameter('tournament', $tournament)
            ->getQuery()
            ->getResult()
        ;
    }
}
