BackendBundle\Entity\Comunicaciones:
    type: entity
    table: comunicaciones
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        observacion:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        imagen:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        imageFile:
            mapping: comunicacion_images
            filename_property: imagen
            nullable: true
        updatedAt:
            type: datetime
            nullable: true    
        enlace:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
    lifecycleCallbacks: {  }
