BackendBundle\Entity\Partidos:
    type: entity
    table: partidos
    indexes:
        fk_partidos_torneos1_idx:
            columns:
                - torneos_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        estado:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        observacion:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
    oneToOne:
        torneos:
            targetEntity: Torneos
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                torneos_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
