BackendBundle\Entity\User:
    type:  entity
    table: fos_user
    id:
        id:
            type: integer
            generator:
                strategy: IDENTITY
    fields:
        facebook_id:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        facebook_access_token:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        google_id:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        google_access_token:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
