BackendBundle\Entity\Usuarios:
    type: entity
    table: usuarios
    indexes:
        fk_usuarios_jugadores_idx:
            columns:
                - jugadores_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        apellido:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        email:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        telefono:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        direccion:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        rol:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        imagen:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
    manyToOne:
        jugadores:
            targetEntity: Jugadores
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                jugadores_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
